### ISSUE TITLE
Installing zsh-users/zsh-completions does not work

### ISSUE THREAD

**Issue by kawpii** [rossmacarthur/sheldon#122]
I did following and opened a new terminal

```
sheldon add zsh-completions --github zsh-users/zsh-completions
```

but auto completions supplied by zsh-completions does not work

Also tried following and opened a new terminal

```
sheldon add zsh-completions --github zsh-users/zsh-completions --dir src --apply PATH source
```

getting following error and zsh-completion does not work

> _arguments:comparguments:325: can only be called from completion function

**Comment by rossmacarthur** [comment]
How Zsh completions work is the directory containing the completions must be added to `fpath` and then `compinit` must be run to compile them. The [`zsh-completions.plugin.zsh`](https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions.plugin.zsh) plugin already adds the `src` directory to `fpath` but it doesn't call `compinit` for you. This is because usually you only want to call `compinit` **once** right at the end of all your modifications to `fpath`, because it can be expensive to recompile.

At present Sheldon does not run `compinit` for you. The easiest way to get this to work is to just add `zsh-completions` normally and make sure `compinit` is called after you source all your Sheldon plugins. 

You could simply add an inline plugin to the end of your `plugins.toml`

```toml
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

# ...

# at the end
[plugins.compinit]
inline = 'autoload -Uz compinit && compinit'
```

Alternatively, you could call `compinit` in your `.zshrc` file:

```sh
# ~/.zshrc

autoload -Uz compinit
eval "$(sheldon source)"
compinit
```

Hope this helps 😄

**Comment by kawpii** [comment]
@rossmacarthur Thanks for reply.

Which way is better to compinit in your opinion? Does adding to `plugins.toml` only runs compinit once, where adding to .zshrc runs always when a new terminal opens?

**Comment by rossmacarthur** [comment]
There is little difference between putting it in Sheldon or `~/.zshrc`, just personal preference. I use [this plugin](https://github.com/rossmacarthur/dotfiles/blob/trunk/src/zsh/plugins/compinit.plugin.zsh) to handle the compinit stuff (code mostly taken from [Oh My Zsh](https://github.com/ohmyzsh/ohmyzsh/blob/master/oh-my-zsh.sh)) code. It has a few small optimizations.

**Comment by kawpii** [comment]
> There is little difference between putting it in Sheldon or ~/.zshrc,

Can you please tell what is that little difference?

**Comment by rossmacarthur** [comment]
I meant there is basically no difference.
